services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FIAP_python
    restart: on-failure
    networks:
      - FIAP-network
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - gestao-postgresql

  gestao-postgresql:
    image: postgres:14
    container_name: FIAP_postgresql
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./contrib/postgresql:/docker-entrypoint-initdb.d
      #- ./db-data/:/var/lib/postgresql/data/
    networks:
      - FIAP-network
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 756M

networks:
  FIAP-network:
    driver: bridge
