services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FIAP_python
    restart: on-failure
    networks:
      - FIAP-network
    env_file:
      - .env
    ports:
      - 8000:8000
  
  gestao-postgresql:
    image: postgres:14
    container_name: FIAP_postgresql
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./contrib/postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--auth-host=md5
    networks:
      - FIAP-network
    deploy:
      resources:
        limits:
          memory: 756M

networks:
  FIAP-network:
      driver: bridge