version: "3"
services:
  api:
    image: python:3.9.18-slim
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - api-network
  db:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foodieflow
    ports:
      - 5432:5432
    networks:
      - api-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

networks:
  api-network:
    driver: bridge
