apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: {{ .Values.python.replicaCount }}
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: "{{ .Values.python.image.repository }}:{{ .Values.python.image.tag }}"
        ports:
        - containerPort: 8000
