apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: {{ .Values.python.service.type }}
  ports:
    - port: {{ .Values.python.service.port }}
      targetPort: 8000
  selector:
    app: python
